name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting (sonarqube)
        fetch-depth: 0
    - name: set up java
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'zulu'
        java-version: 17
    - name: run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2.28.0
      with:
        api-level: 31
        arch: x86_64
        script: ./gradlew connectedCheck
    - name: run unitTest lint detekt and generate jacoco report
      run: ./gradlew lintDebug detektDebug testDebugUnitTest jacocoTestDebugUnitTestReport
    - name: Sonarqube
      run: ./gradlew sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
