name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting (sonarqube)
        fetch-depth: 0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2.14.3
      with:
        api-level: 29
        script: ./gradlew connectedCheck
    - name: run unitTest lint detekt and generate jacoco report
      run: ./gradlew lintDebug detektDebug testDebugUnitTest jacocoTestDebugUnitTestReport
    - name: set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Sonarqube
      run: ./gradlew sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
