name: Android Instrumented

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2.14.3
      with:
        api-level: 29
        script: ./gradlew connectedCheck
